import { describe, expect, it } from "vitest";
import {
  canCompleteWithMockWorker,
  defaultGenerationModels,
  defaultGenerationModelValues,
  falAuraSrModelId,
  falVideoUpscalerModelId,
  falWanVideoToVideoModelId,
  generatedAssetHasRerunnableModel,
  generationAgentModePrompt,
  generationAudioPromptCategory,
  generationModeFromAsset,
  generationModeLabel,
  generationModelAcceptsSelectedSourceVideo,
  generationModelAcceptsTypedAudioReferences,
  generationModelAcceptsTypedVisualReferences,
  generationModelFromValue,
  generationModelLabel,
  generationModelMinPromptLength,
  generationModelOptions,
  generationModelOptionsFromCatalog,
  generationModelPreservesSelectedSourceVideoSettings,
  generationModelReferenceLimits,
  generationModelRequiresFirstFrame,
  generationModelRequiresSelectedSourceVideo,
  generationModelSupportsAudioToggle,
  generationModelSupportsFrameReferences,
  generationModelSupportsInstrumental,
  generationModelSupportsLyrics,
  generationModelSupportsReferenceMedia,
  generationModelSupportsStyleInstructions,
  generationModelUsesExclusiveFrameReferenceModes,
  generationModelUsesTypedImageReferences,
  generationModelValue,
  generationPromptPlaceholder,
  generationPromptReadinessMessage,
  generationProviderDisplayName,
  generationRequestModel,
  isGenerationModelValueForMode,
  organizeMediaPrompt,
  selectedGenerationModel,
  timelineTargetKindLabel,
  timelineTargetMode,
  validGenerationTimelineSourceRange,
  videoInputAudioCategory,
} from "@/lib/generation/provider-rules";
import type {
  GenerationModelCatalog,
  GenerationModelOption,
  MediaGenerationMode,
} from "@/lib/generation/types";
import type { GeneratedAsset } from "@/lib/project";
import { fixtureGeneratedAsset, fixtureProject } from "@/test-utils/editor-fixtures";

const modes = ["image", "video", "audio"] as const;

// Catalog options in the flattened shape generationModelCatalogFromPayload
// produces: the payload fields plus the uiCapabilities spread on top.
const catalogVideoCapabilities = {
  durations: [5, 10],
  resolutions: ["720p"],
  aspectRatios: ["16:9"],
  supportsFirstFrame: true,
  supportsLastFrame: false,
  maxReferenceImages: 1,
  maxReferenceVideos: 0,
  maxReferenceAudios: 2,
  maxTotalReferences: 2,
  maxCombinedVideoRefSeconds: null,
  maxCombinedAudioRefSeconds: 10,
  framesAndReferencesExclusive: true,
  referenceTagNoun: "reference",
  requiresSourceVideo: true,
  requiresReferenceImage: true,
};

const catalogAudioCapabilities = {
  category: "tts",
  voices: ["narrator"],
  defaultVoice: "narrator",
  supportsLyrics: false,
  supportsInstrumental: false,
  supportsStyleInstructions: false,
  durations: null,
  minPromptLength: 25,
  inputs: ["text"],
  promptLabel: "Script",
  minSeconds: 1,
  maxSeconds: 60,
};

const catalog: GenerationModelCatalog = {
  video: [
    {
      provider: "fal.ai",
      id: "fal-ai/wan-25-preview/text-to-video",
      kind: "video",
      displayName: "Catalog Wan Text to Video",
      ...catalogVideoCapabilities,
      supportsReferences: true,
      supportsSourceVideo: false,
      uiCapabilities: catalogVideoCapabilities,
      cancellationCapability: "provider",
      paidOnly: false,
    } as GenerationModelOption,
  ],
  audio: [
    {
      provider: "minimax",
      id: "minimax-music-v2.6",
      kind: "audio",
      displayName: "  Catalog MiniMax Speech  ",
      ...catalogAudioCapabilities,
      uiCapabilities: catalogAudioCapabilities,
      cancellationCapability: "local",
      paidOnly: true,
    } as unknown as GenerationModelOption,
  ],
  upscale: [{ provider: "catalog", id: "catalog-upscaler", kind: "upscale" }],
};

const catalogOptions = generationModelOptionsFromCatalog(catalog);

function optionRow(mode: MediaGenerationMode, option: GenerationModelOption) {
  return {
    value: generationModelValue(option),
    label: generationModelLabel(option),
    displayProvider: generationProviderDisplayName(option.provider),
    supportsReferenceMedia: generationModelSupportsReferenceMedia(mode, option),
    usesTypedImageReferences: generationModelUsesTypedImageReferences(mode, option),
    requiresSelectedSourceVideo: generationModelRequiresSelectedSourceVideo(mode, option),
    acceptsSelectedSourceVideo: generationModelAcceptsSelectedSourceVideo(mode, option),
    preservesSelectedSourceVideoSettings: generationModelPreservesSelectedSourceVideoSettings(
      mode,
      option,
    ),
    supportsInstrumental: generationModelSupportsInstrumental(mode, option),
    supportsAudioToggle: generationModelSupportsAudioToggle(mode, option),
    supportsLyrics: generationModelSupportsLyrics(mode, option),
    supportsStyleInstructions: generationModelSupportsStyleInstructions(mode, option),
    requiresFirstFrame: generationModelRequiresFirstFrame(mode, option),
    supportsFrameReferences: generationModelSupportsFrameReferences(mode, option),
    usesExclusiveFrameReferenceModes: generationModelUsesExclusiveFrameReferenceModes(
      mode,
      option,
    ),
    acceptsTypedAudioReferences: generationModelAcceptsTypedAudioReferences(mode, option),
    acceptsTypedVisualReferences: generationModelAcceptsTypedVisualReferences(mode, option),
    referenceLimits: generationModelReferenceLimits(mode, option),
    videoInputAudioCategory: videoInputAudioCategory(option),
    audioPromptCategory: generationAudioPromptCategory(option),
    minPromptLength: generationModelMinPromptLength(mode, option),
    placeholder: generationPromptPlaceholder(mode, option),
    agentModePrompt: generationAgentModePrompt(mode, option),
    readinessEmpty: generationPromptReadinessMessage(mode, option, ""),
    readinessShort: generationPromptReadinessMessage(mode, option, "a short prompt"),
  };
}

function matrix(
  mode: MediaGenerationMode,
  options: readonly GenerationModelOption[],
  providers?: readonly string[],
) {
  return options
    .filter((option) => !providers || providers.includes(option.provider))
    .map((option) => optionRow(mode, option));
}

describe("generation model option matrix", () => {
  it("records image fallback options", () => {
    expect(matrix("image", generationModelOptions.image)).toMatchInlineSnapshot(`
      [
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "OpenAI",
          "label": "openai/gpt-image-2",
          "minPromptLength": 1,
          "placeholder": "Describe the image",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "openai:gpt-image-2",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal-ai/nano-banana-pro/edit",
          "minPromptLength": 1,
          "placeholder": "Describe the image",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": true,
          "value": "fal.ai:fal-ai/nano-banana-pro/edit",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal-ai/flux/schnell",
          "minPromptLength": 1,
          "placeholder": "Describe the image",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:fal-ai/flux/schnell",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal-ai/krea-2/turbo",
          "minPromptLength": 1,
          "placeholder": "Describe the image",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:fal-ai/krea-2/turbo",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal-ai/recraft/v3/text-to-image",
          "minPromptLength": 1,
          "placeholder": "Describe the image",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:fal-ai/recraft/v3/text-to-image",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "Replicate",
          "label": "replicate/black-forest-labs/flux-schnell",
          "minPromptLength": 1,
          "placeholder": "Describe the image",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "replicate:black-forest-labs/flux-schnell",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "Replicate",
          "label": "replicate/black-forest-labs/flux-dev",
          "minPromptLength": 1,
          "placeholder": "Describe the image",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "replicate:black-forest-labs/flux-dev",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "Replicate",
          "label": "replicate/black-forest-labs/flux-1.1-pro",
          "minPromptLength": 1,
          "placeholder": "Describe the image",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "replicate:black-forest-labs/flux-1.1-pro",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "Replicate",
          "label": "replicate/black-forest-labs/flux-1.1-pro-ultra",
          "minPromptLength": 1,
          "placeholder": "Describe the image",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "replicate:black-forest-labs/flux-1.1-pro-ultra",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "OpenAI",
          "label": "openai/gpt-image-1.5",
          "minPromptLength": 1,
          "placeholder": "Describe the image",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": true,
          "value": "openai:gpt-image-1.5",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "xAI",
          "label": "xai/grok-imagine-image-quality",
          "minPromptLength": 1,
          "placeholder": "Describe the image",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": true,
          "value": "xai:grok-imagine-image-quality",
          "videoInputAudioCategory": "music",
        },
      ]
    `);
  });

  it("records fal.ai video fallback options", () => {
    expect(matrix("video", generationModelOptions.video, ["fal.ai"])).toMatchInlineSnapshot(`
      [
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": true,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal-ai/wan-25-preview/text-to-video",
          "minPromptLength": 1,
          "placeholder": "Describe the video",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": {
            "maxCombinedAudioRefSeconds": null,
            "maxCombinedVideoRefSeconds": null,
            "maxReferenceAudios": 1,
            "maxReferenceImages": 0,
            "maxReferenceVideos": 0,
            "maxTotalReferences": 1,
            "requiresReferenceImage": false,
          },
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": true,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:fal-ai/wan-25-preview/text-to-video",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": true,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal-ai/wan/v2.7/image-to-video",
          "minPromptLength": 1,
          "placeholder": "Describe the video",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": {
            "maxCombinedAudioRefSeconds": null,
            "maxCombinedVideoRefSeconds": null,
            "maxReferenceAudios": 1,
            "maxReferenceImages": 2,
            "maxReferenceVideos": 1,
            "maxTotalReferences": null,
            "requiresReferenceImage": false,
          },
          "requiresFirstFrame": true,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": true,
          "supportsFrameReferences": true,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:fal-ai/wan/v2.7/image-to-video",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": true,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal-ai/wan/v2.7/reference-to-video",
          "minPromptLength": 1,
          "placeholder": "Describe the video",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": {
            "maxCombinedAudioRefSeconds": null,
            "maxCombinedVideoRefSeconds": null,
            "maxReferenceAudios": 0,
            "maxReferenceImages": 4,
            "maxReferenceVideos": 3,
            "maxTotalReferences": null,
            "requiresReferenceImage": true,
          },
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": true,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:fal-ai/wan/v2.7/reference-to-video",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": true,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": true,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal-ai/wan/v2.2-a14b/video-to-video",
          "minPromptLength": 1,
          "placeholder": "Describe the video",
          "preservesSelectedSourceVideoSettings": true,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": {
            "maxCombinedAudioRefSeconds": null,
            "maxCombinedVideoRefSeconds": null,
            "maxReferenceAudios": 0,
            "maxReferenceImages": 1,
            "maxReferenceVideos": 0,
            "maxTotalReferences": null,
            "requiresReferenceImage": false,
          },
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": true,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:fal-ai/wan/v2.2-a14b/video-to-video",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal-ai/kling-video/v3/standard/text-to-video",
          "minPromptLength": 1,
          "placeholder": "Describe the video",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": {
            "maxCombinedAudioRefSeconds": null,
            "maxCombinedVideoRefSeconds": null,
            "maxReferenceAudios": 0,
            "maxReferenceImages": 0,
            "maxReferenceVideos": 0,
            "maxTotalReferences": 0,
            "requiresReferenceImage": false,
          },
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": true,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:fal-ai/kling-video/v3/standard/text-to-video",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal-ai/kling-video/v3/pro/image-to-video",
          "minPromptLength": 1,
          "placeholder": "Describe the video",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": {
            "maxCombinedAudioRefSeconds": null,
            "maxCombinedVideoRefSeconds": null,
            "maxReferenceAudios": 0,
            "maxReferenceImages": 2,
            "maxReferenceVideos": 0,
            "maxTotalReferences": null,
            "requiresReferenceImage": false,
          },
          "requiresFirstFrame": true,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": true,
          "supportsFrameReferences": true,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:fal-ai/kling-video/v3/pro/image-to-video",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": true,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": true,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal-ai/kling-video/v3/pro/motion-control",
          "minPromptLength": 1,
          "placeholder": "Describe the video",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": {
            "maxCombinedAudioRefSeconds": null,
            "maxCombinedVideoRefSeconds": null,
            "maxReferenceAudios": 0,
            "maxReferenceImages": 1,
            "maxReferenceVideos": 0,
            "maxTotalReferences": null,
            "requiresReferenceImage": true,
          },
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": true,
          "supportsAudioToggle": true,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:fal-ai/kling-video/v3/pro/motion-control",
          "videoInputAudioCategory": "music",
        },
      ]
    `);
  });

  it("records non-fal video fallback options", () => {
    expect(
      matrix("video", generationModelOptions.video, ["replicate", "xai", "google"]),
    ).toMatchInlineSnapshot(`
      [
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": true,
          "acceptsTypedVisualReferences": true,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "Replicate",
          "label": "replicate/bytedance/seedance-2.0-fast",
          "minPromptLength": 1,
          "placeholder": "Describe the video",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": {
            "maxCombinedAudioRefSeconds": 15,
            "maxCombinedVideoRefSeconds": 15,
            "maxReferenceAudios": 3,
            "maxReferenceImages": 4,
            "maxReferenceVideos": 3,
            "maxTotalReferences": 6,
            "requiresReferenceImage": false,
          },
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": true,
          "supportsFrameReferences": true,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": true,
          "usesTypedImageReferences": false,
          "value": "replicate:bytedance/seedance-2.0-fast",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": true,
          "acceptsTypedVisualReferences": true,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "Replicate",
          "label": "replicate/bytedance/seedance-2.0",
          "minPromptLength": 1,
          "placeholder": "Describe the video",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": {
            "maxCombinedAudioRefSeconds": 15,
            "maxCombinedVideoRefSeconds": 15,
            "maxReferenceAudios": 3,
            "maxReferenceImages": 4,
            "maxReferenceVideos": 3,
            "maxTotalReferences": 6,
            "requiresReferenceImage": false,
          },
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": true,
          "supportsFrameReferences": true,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": true,
          "usesTypedImageReferences": false,
          "value": "replicate:bytedance/seedance-2.0",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": true,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": true,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "xAI",
          "label": "xai/grok-imagine-video",
          "minPromptLength": 1,
          "placeholder": "Describe the video",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": {
            "maxCombinedAudioRefSeconds": null,
            "maxCombinedVideoRefSeconds": null,
            "maxReferenceAudios": 0,
            "maxReferenceImages": 7,
            "maxReferenceVideos": 0,
            "maxTotalReferences": 7,
            "requiresReferenceImage": false,
          },
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": true,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": true,
          "usesTypedImageReferences": false,
          "value": "xai:grok-imagine-video",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": true,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "Google",
          "label": "google/veo3.1-fast",
          "minPromptLength": 1,
          "placeholder": "Describe the video",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": {
            "maxCombinedAudioRefSeconds": null,
            "maxCombinedVideoRefSeconds": null,
            "maxReferenceAudios": 0,
            "maxReferenceImages": 3,
            "maxReferenceVideos": 0,
            "maxTotalReferences": 3,
            "requiresReferenceImage": false,
          },
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": true,
          "supportsFrameReferences": true,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": true,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "google:veo3.1-fast",
          "videoInputAudioCategory": "music",
        },
      ]
    `);
  });

  it("records audio fallback options", () => {
    expect(matrix("audio", generationModelOptions.audio)).toMatchInlineSnapshot(`
      [
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal.ai/bytedance/seed-audio-1.0",
          "minPromptLength": 1,
          "placeholder": "Describe the sound",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:bytedance/seed-audio-1.0",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": "Generate music for my timeline and place it on an audio track aligned to the edit.",
          "audioPromptCategory": "music",
          "displayProvider": "fal.ai",
          "label": "fal.ai/sonilo/v1.1/text-to-music",
          "minPromptLength": 1,
          "placeholder": "Describe the music style or mood",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": true,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": true,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:sonilo/v1.1/text-to-music",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": true,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": "Score my timeline with music that matches the visuals. Use a video-to-music model on the full timeline span so the music follows the edit, and place it on an audio track.",
          "audioPromptCategory": "music",
          "displayProvider": "fal.ai",
          "label": "fal.ai/sonilo/v1.1/video-to-music",
          "minPromptLength": 1,
          "placeholder": "Describe the music style or mood",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": true,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:sonilo/v1.1/video-to-music",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": true,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "sfx",
          "displayProvider": "fal.ai",
          "label": "fal.ai/mirelo-ai/sfx-v1.5/video-to-audio",
          "minPromptLength": 1,
          "placeholder": "Describe the sound",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": true,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": false,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "fal.ai:mirelo-ai/sfx-v1.5/video-to-audio",
          "videoInputAudioCategory": "sfx",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "tts",
          "displayProvider": "OpenAI",
          "label": "openai/gpt-4o-mini-tts",
          "minPromptLength": 1,
          "placeholder": "Text to speak",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": true,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "openai:gpt-4o-mini-tts",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "tts",
          "displayProvider": "ElevenLabs",
          "label": "elevenlabs/elevenlabs-tts-v3",
          "minPromptLength": 1,
          "placeholder": "Text to speak",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": true,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "elevenlabs:elevenlabs-tts-v3",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": "Generate music for my timeline and place it on an audio track aligned to the edit.",
          "audioPromptCategory": "music",
          "displayProvider": "ElevenLabs",
          "label": "elevenlabs/elevenlabs-music",
          "minPromptLength": 1,
          "placeholder": "Describe the music style or mood",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": true,
          "supportsLyrics": true,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": true,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "elevenlabs:elevenlabs-music",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": "Generate music for my timeline and place it on an audio track aligned to the edit.",
          "audioPromptCategory": "music",
          "displayProvider": "MiniMax",
          "label": "minimax/minimax-music-v2.6",
          "minPromptLength": 10,
          "placeholder": "Describe the music style or mood (min 10 chars)",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt needs 10 characters",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": true,
          "supportsLyrics": true,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": true,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "minimax:minimax-music-v2.6",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": null,
          "audioPromptCategory": "tts",
          "displayProvider": "Google",
          "label": "google/gemini-3.1-flash-tts-preview",
          "minPromptLength": 1,
          "placeholder": "Text to speak",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": false,
          "supportsLyrics": false,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": true,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "google:gemini-3.1-flash-tts-preview",
          "videoInputAudioCategory": "music",
        },
        {
          "acceptsSelectedSourceVideo": false,
          "acceptsTypedAudioReferences": false,
          "acceptsTypedVisualReferences": false,
          "agentModePrompt": "Generate music for my timeline and place it on an audio track aligned to the edit.",
          "audioPromptCategory": "music",
          "displayProvider": "Google",
          "label": "google/lyria3-pro",
          "minPromptLength": 1,
          "placeholder": "Describe the music style or mood",
          "preservesSelectedSourceVideoSettings": false,
          "readinessEmpty": "Prompt required",
          "readinessShort": null,
          "referenceLimits": null,
          "requiresFirstFrame": false,
          "requiresSelectedSourceVideo": false,
          "supportsAudioToggle": false,
          "supportsFrameReferences": false,
          "supportsInstrumental": true,
          "supportsLyrics": true,
          "supportsReferenceMedia": false,
          "supportsStyleInstructions": true,
          "usesExclusiveFrameReferenceModes": false,
          "usesTypedImageReferences": false,
          "value": "google:lyria3-pro",
          "videoInputAudioCategory": "music",
        },
      ]
    `);
  });

  it("records catalog options whose uiCapabilities override fallback rules", () => {
    expect(catalogOptions.image).toBe(generationModelOptions.image);
    expect({
      video: matrix("video", catalogOptions.video),
      audio: matrix("audio", catalogOptions.audio),
    }).toMatchInlineSnapshot(`
      {
        "audio": [
          {
            "acceptsSelectedSourceVideo": false,
            "acceptsTypedAudioReferences": false,
            "acceptsTypedVisualReferences": false,
            "agentModePrompt": null,
            "audioPromptCategory": "tts",
            "displayProvider": "MiniMax",
            "label": "Catalog MiniMax Speech",
            "minPromptLength": 25,
            "placeholder": "Text to speak (min 25 chars)",
            "preservesSelectedSourceVideoSettings": false,
            "readinessEmpty": "Prompt needs 25 characters",
            "readinessShort": "Prompt needs 25 characters",
            "referenceLimits": null,
            "requiresFirstFrame": false,
            "requiresSelectedSourceVideo": false,
            "supportsAudioToggle": false,
            "supportsFrameReferences": false,
            "supportsInstrumental": false,
            "supportsLyrics": false,
            "supportsReferenceMedia": false,
            "supportsStyleInstructions": false,
            "usesExclusiveFrameReferenceModes": false,
            "usesTypedImageReferences": false,
            "value": "minimax:minimax-music-v2.6",
            "videoInputAudioCategory": "music",
          },
        ],
        "video": [
          {
            "acceptsSelectedSourceVideo": true,
            "acceptsTypedAudioReferences": true,
            "acceptsTypedVisualReferences": true,
            "agentModePrompt": null,
            "audioPromptCategory": "sfx",
            "displayProvider": "fal.ai",
            "label": "Catalog Wan Text to Video",
            "minPromptLength": 1,
            "placeholder": "Describe the video",
            "preservesSelectedSourceVideoSettings": false,
            "readinessEmpty": "Prompt required",
            "readinessShort": null,
            "referenceLimits": {
              "maxCombinedAudioRefSeconds": 10,
              "maxCombinedVideoRefSeconds": null,
              "maxReferenceAudios": 2,
              "maxReferenceImages": 1,
              "maxReferenceVideos": 0,
              "maxTotalReferences": 2,
              "requiresReferenceImage": true,
            },
            "requiresFirstFrame": true,
            "requiresSelectedSourceVideo": true,
            "supportsAudioToggle": true,
            "supportsFrameReferences": true,
            "supportsInstrumental": false,
            "supportsLyrics": false,
            "supportsReferenceMedia": true,
            "supportsStyleInstructions": false,
            "usesExclusiveFrameReferenceModes": true,
            "usesTypedImageReferences": false,
            "value": "fal.ai:fal-ai/wan-25-preview/text-to-video",
            "videoInputAudioCategory": "music",
          },
        ],
      }
    `);
  });

  it("falls back to the built-in options for a null catalog", () => {
    const options = generationModelOptionsFromCatalog(null);
    expect(options.image).toBe(generationModelOptions.image);
    expect(options.video).toBe(generationModelOptions.video);
    expect(options.audio).toBe(generationModelOptions.audio);
    expect(generationModelOptionsFromCatalog({ image: [], video: [] }).video).toBe(
      generationModelOptions.video,
    );
  });
});

describe("generation model selection", () => {
  it("records defaults, mode labels and timeline target modes", () => {
    expect({
      defaultGenerationModels,
      defaultGenerationModelValues,
      modes: modes.map((mode) => ({
        mode,
        label: generationModeLabel(mode),
        timelineTargetMode: timelineTargetMode(mode),
        timelineTargetKindLabel: timelineTargetKindLabel(mode),
      })),
      organizeMediaPrompt,
    }).toMatchInlineSnapshot(`
      {
        "defaultGenerationModelValues": {
          "audio": "fal.ai:bytedance/seed-audio-1.0",
          "image": "openai:gpt-image-2",
          "video": "replicate:bytedance/seedance-2.0-fast",
        },
        "defaultGenerationModels": {
          "audio": {
            "id": "bytedance/seed-audio-1.0",
            "provider": "fal.ai",
          },
          "image": {
            "id": "gpt-image-2",
            "provider": "openai",
          },
          "video": {
            "id": "bytedance/seedance-2.0-fast",
            "provider": "replicate",
          },
        },
        "modes": [
          {
            "label": "Image",
            "mode": "image",
            "timelineTargetKindLabel": "video",
            "timelineTargetMode": "video",
          },
          {
            "label": "Video",
            "mode": "video",
            "timelineTargetKindLabel": "video",
            "timelineTargetMode": "video",
          },
          {
            "label": "Audio",
            "mode": "audio",
            "timelineTargetKindLabel": "audio",
            "timelineTargetMode": "audio",
          },
        ],
        "organizeMediaPrompt": "Organize the current project media into clear folders using media metadata and content. Do not delete any media. Do not add, remove, move, trim, or otherwise change timeline items. Return reviewed project actions only; do not mutate canonical files directly.",
      }
    `);
  });

  it("resolves model values against fallback and catalog options", () => {
    expect({
      requestModel: generationRequestModel({
        provider: "fal.ai",
        id: falWanVideoToVideoModelId,
        displayName: "Extra",
      } as GenerationModelOption),
      fromKnownValue: generationModelFromValue("video", "xai:grok-imagine-video"),
      fromUnknownValue: generationModelFromValue("video", "nope:missing"),
      fromValueInCatalog: generationModelFromValue(
        "audio",
        "fal.ai:bytedance/seed-audio-1.0",
        catalogOptions,
      ).id,
      fromValueEmptyOptions: generationModelFromValue("image", "openai:gpt-image-2", {
        image: [],
        video: [],
        audio: [],
      }),
      selectedWithoutValue: selectedGenerationModel("audio"),
      selectedWithEmptyValue: selectedGenerationModel("image", ""),
      selectedWithValue: selectedGenerationModel("image", "xai:grok-imagine-image-quality"),
      selectedFromCatalog: selectedGenerationModel("video", undefined, catalogOptions).id,
      valueForModeMatches: isGenerationModelValueForMode("image", "openai:gpt-image-1.5"),
      valueForWrongMode: isGenerationModelValueForMode("video", "openai:gpt-image-1.5"),
      valueForModeInCatalog: isGenerationModelValueForMode(
        "video",
        "replicate:bytedance/seedance-2.0-fast",
        catalogOptions,
      ),
      providerNames: [" OpenAI ", "fal.ai", "XAI", "Custom Provider ", ""].map((provider) =>
        generationProviderDisplayName(provider),
      ),
      labels: [
        { provider: "fal.ai", id: "fal-ai/flux/schnell" },
        { provider: "fal.ai", id: "sonilo/v1.1/text-to-music" },
        { provider: "openai", id: "gpt-image-2", displayName: "   " },
        { provider: "openai", id: "gpt-image-2", displayName: " GPT Image " },
      ].map((model) => generationModelLabel(model)),
    }).toMatchInlineSnapshot(`
      {
        "fromKnownValue": {
          "id": "grok-imagine-video",
          "provider": "xai",
        },
        "fromUnknownValue": {
          "id": "bytedance/seedance-2.0-fast",
          "provider": "replicate",
        },
        "fromValueEmptyOptions": {
          "id": "gpt-image-2",
          "provider": "openai",
        },
        "fromValueInCatalog": "minimax-music-v2.6",
        "labels": [
          "fal-ai/flux/schnell",
          "fal.ai/sonilo/v1.1/text-to-music",
          "openai/gpt-image-2",
          "GPT Image",
        ],
        "providerNames": [
          "OpenAI",
          "fal.ai",
          "xAI",
          "Custom Provider",
          "",
        ],
        "requestModel": {
          "id": "fal-ai/wan/v2.2-a14b/video-to-video",
          "provider": "fal.ai",
        },
        "selectedFromCatalog": "fal-ai/wan-25-preview/text-to-video",
        "selectedWithEmptyValue": {
          "id": "gpt-image-2",
          "provider": "openai",
        },
        "selectedWithValue": {
          "id": "grok-imagine-image-quality",
          "provider": "xai",
        },
        "selectedWithoutValue": {
          "id": "bytedance/seed-audio-1.0",
          "provider": "fal.ai",
        },
        "valueForModeInCatalog": false,
        "valueForModeMatches": true,
        "valueForWrongMode": false,
      }
    `);
  });
});

describe("validGenerationTimelineSourceRange", () => {
  const sourceVideoModel = { provider: "fal.ai", id: "sonilo/v1.1/video-to-music" };

  it("records valid, zero-length, non-finite and non-source-video ranges", () => {
    expect({
      valid: validGenerationTimelineSourceRange("audio", sourceVideoModel, {
        label: "Timeline 0:01-0:05",
        startSeconds: 1.23456,
        endSeconds: 5.00049,
      }),
      zeroLength: validGenerationTimelineSourceRange("audio", sourceVideoModel, {
        label: "Zero",
        startSeconds: 3,
        endSeconds: 3,
      }),
      negativeStart: validGenerationTimelineSourceRange("audio", sourceVideoModel, {
        label: "Negative",
        startSeconds: -1,
        endSeconds: 3,
      }),
      nullBounds: validGenerationTimelineSourceRange("audio", sourceVideoModel, {
        label: "Null bounds",
        startSeconds: null,
        endSeconds: null,
      } as unknown as { label: string; startSeconds: number; endSeconds: number }),
      infiniteEnd: validGenerationTimelineSourceRange("audio", sourceVideoModel, {
        label: "Infinite",
        startSeconds: 0,
        endSeconds: Number.POSITIVE_INFINITY,
      }),
      nullRange: validGenerationTimelineSourceRange("audio", sourceVideoModel, null),
      undefinedRange: validGenerationTimelineSourceRange("audio", sourceVideoModel, undefined),
      modelWithoutSourceVideo: validGenerationTimelineSourceRange(
        "audio",
        { provider: "fal.ai", id: "sonilo/v1.1/text-to-music" },
        { label: "Valid", startSeconds: 0, endSeconds: 2 },
      ),
      wrongMode: validGenerationTimelineSourceRange("video", sourceVideoModel, {
        label: "Valid",
        startSeconds: 0,
        endSeconds: 2,
      }),
      videoToVideo: validGenerationTimelineSourceRange(
        "video",
        { provider: "fal.ai", id: falWanVideoToVideoModelId },
        { label: "Video", startSeconds: 0.5, endSeconds: 2.5 },
      ),
    }).toMatchInlineSnapshot(`
      {
        "infiniteEnd": null,
        "modelWithoutSourceVideo": null,
        "negativeStart": null,
        "nullBounds": null,
        "nullRange": null,
        "undefinedRange": null,
        "valid": {
          "endSeconds": 5,
          "label": "Timeline 0:01-0:05",
          "startSeconds": 1.235,
        },
        "videoToVideo": {
          "endSeconds": 2.5,
          "label": "Video",
          "startSeconds": 0.5,
        },
        "wrongMode": null,
        "zeroLength": null,
      }
    `);
  });
});

describe("generated asset model rules", () => {
  function assetVariants(): Array<{ name: string; asset: GeneratedAsset }> {
    const base = fixtureGeneratedAsset(fixtureProject());
    return [
      { name: "fixture", asset: base },
      { name: "image kind", asset: { ...base, kind: "image" } },
      { name: "video kind", asset: { ...base, kind: "video" } },
      { name: "audio kind", asset: { ...base, kind: "audio" } },
      {
        name: "elevenlabs provider",
        asset: { ...base, model: { provider: "elevenlabs", id: "elevenlabs-tts-v3" } },
      },
      {
        name: "no dimensions",
        asset: { ...base, settings: { ...base.settings, width: null, height: null } },
      },
      {
        name: "no duration or fps",
        asset: {
          ...base,
          settings: { ...base.settings, durationSeconds: null, fps: null },
        },
      },
      {
        name: "fallback video model",
        asset: { ...base, model: { provider: "xai", id: "grok-imagine-video" } },
      },
      {
        name: "fallback image model on video kind",
        asset: { ...base, kind: "video", model: { provider: "openai", id: "gpt-image-2" } },
      },
      {
        name: "mock fal image model",
        asset: {
          ...base,
          kind: "image",
          model: { provider: "fal.ai", id: "fal-ai/flux/schnell" },
        },
      },
      {
        name: "mock fal video model",
        asset: { ...base, model: { provider: "fal.ai", id: "fal-ai/wan-25-preview/text-to-video" } },
      },
      {
        name: "mock sonilo on wrong provider",
        asset: { ...base, kind: "audio", model: { provider: "replicate", id: "sonilo/v1.1/text-to-music" } },
      },
      {
        name: "aura-sr upscale",
        asset: { ...base, kind: "image", model: { provider: "fal.ai", id: falAuraSrModelId } },
      },
      {
        name: "video upscaler",
        asset: { ...base, model: { provider: "fal.ai", id: falVideoUpscalerModelId } },
      },
      {
        name: "catalog upscaler",
        asset: { ...base, kind: "image", model: { provider: "catalog", id: "catalog-upscaler" } },
      },
      {
        name: "unknown provider",
        asset: { ...base, model: { provider: "mystery", id: "mystery-model" } },
      },
    ];
  }

  it("records mode, rerunnable and mock-completion rules per asset variant", () => {
    expect(
      assetVariants().map(({ name, asset }) => ({
        name,
        mode: generationModeFromAsset(asset),
        rerunnableWithoutCatalog: generatedAssetHasRerunnableModel(
          asset,
          null,
          generationModelOptions,
        ),
        rerunnableWithCatalog: generatedAssetHasRerunnableModel(asset, catalog, catalogOptions),
        rerunnableWithEmptyCatalog: generatedAssetHasRerunnableModel(
          asset,
          {},
          generationModelOptions,
        ),
        mockCompletable: canCompleteWithMockWorker(asset),
      })),
    ).toMatchInlineSnapshot(`
      [
        {
          "mockCompletable": false,
          "mode": "video",
          "name": "fixture",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": false,
        },
        {
          "mockCompletable": false,
          "mode": "image",
          "name": "image kind",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": false,
        },
        {
          "mockCompletable": false,
          "mode": "video",
          "name": "video kind",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": false,
        },
        {
          "mockCompletable": false,
          "mode": "audio",
          "name": "audio kind",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": false,
        },
        {
          "mockCompletable": false,
          "mode": "audio",
          "name": "elevenlabs provider",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": true,
          "rerunnableWithoutCatalog": true,
        },
        {
          "mockCompletable": false,
          "mode": "audio",
          "name": "no dimensions",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": false,
        },
        {
          "mockCompletable": false,
          "mode": "image",
          "name": "no duration or fps",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": false,
        },
        {
          "mockCompletable": false,
          "mode": "video",
          "name": "fallback video model",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": true,
          "rerunnableWithoutCatalog": true,
        },
        {
          "mockCompletable": true,
          "mode": "video",
          "name": "fallback image model on video kind",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": false,
        },
        {
          "mockCompletable": true,
          "mode": "image",
          "name": "mock fal image model",
          "rerunnableWithCatalog": true,
          "rerunnableWithEmptyCatalog": true,
          "rerunnableWithoutCatalog": true,
        },
        {
          "mockCompletable": true,
          "mode": "video",
          "name": "mock fal video model",
          "rerunnableWithCatalog": true,
          "rerunnableWithEmptyCatalog": true,
          "rerunnableWithoutCatalog": true,
        },
        {
          "mockCompletable": false,
          "mode": "audio",
          "name": "mock sonilo on wrong provider",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": false,
        },
        {
          "mockCompletable": false,
          "mode": "image",
          "name": "aura-sr upscale",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": true,
        },
        {
          "mockCompletable": false,
          "mode": "video",
          "name": "video upscaler",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": true,
        },
        {
          "mockCompletable": false,
          "mode": "image",
          "name": "catalog upscaler",
          "rerunnableWithCatalog": true,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": false,
        },
        {
          "mockCompletable": false,
          "mode": "video",
          "name": "unknown provider",
          "rerunnableWithCatalog": false,
          "rerunnableWithEmptyCatalog": false,
          "rerunnableWithoutCatalog": false,
        },
      ]
    `);
  });
});
