import { describe, expect, it } from "vitest";
import {
  boundedGenerationDurationValue,
  fallbackVideoResolutionOption,
  generationAspectRatioOptionsForModel,
  generationDurationBoundsForModel,
  generationDurationOptionsForModel,
  generationDurationValue,
  generationModelMaxImages,
  generationQualityLabel,
  generationQualityOptionsForModel,
  generationResolutionLabel,
  generationResolutionOptionsForModel,
  generationResolutionValue,
  generationVoiceOptionsForModel,
  imageGenerationProviderResolution,
  isGenerationAspectRatio,
  selectedBoundedGenerationDurationSeconds,
  selectedBoundedGenerationDurationValue,
  selectedGenerationQualityValue,
  selectedGenerationResolutionValue,
  selectedGenerationSettings,
  selectedGenerationVoice,
  selectedImageCount,
} from "@/lib/generation/settings-options";
import {
  elevenLabsTtsModelId,
  falFluxSchnellModelId,
  falNanoBananaProEditModelId,
  falWanVideoToVideoModelId,
  generationModelOptions,
  googleGeminiTtsModelId,
  googleVeo31FastModelId,
  openAiGptImage2ModelId,
  openAiGptImageEditModelId,
  openAiTtsModelId,
  xAiGrokImageQualityModelId,
} from "@/lib/generation/provider-rules";
import type {
  GenerationModelOption,
  GenerationResolutionOption,
  MediaGenerationMode,
} from "@/lib/generation/types";

function resolutionRow(mode: MediaGenerationMode, option: GenerationResolutionOption) {
  return `${option.value} ${option.width}x${option.height} provider=${option.providerResolution} label=${
    option.label ?? "-"
  } display=${generationResolutionLabel(mode, option)}`;
}

function settingsRow(mode: MediaGenerationMode, option: GenerationModelOption) {
  const durationOptions = generationDurationOptionsForModel(mode, option);
  const aspectOptions = generationAspectRatioOptionsForModel(mode, option);
  const resolutionOptions = generationResolutionOptionsForModel(mode, option);
  const qualityOptions = generationQualityOptionsForModel(mode, option);
  const voiceOptions = generationVoiceOptionsForModel(mode, option);
  const settings = (generateAudio: boolean) =>
    selectedGenerationSettings(
      mode,
      option,
      durationOptions[0]?.value ?? "",
      aspectOptions[0] ?? "",
      resolutionOptions[0]?.value ?? "",
      "1",
      generateAudio,
      false,
      "",
      "la la",
      "warm",
      qualityOptions[0] ?? "",
    );
  return {
    model: `${option.provider}:${option.id}`,
    durationOptions: durationOptions.map((duration) => `${duration.value}=${duration.seconds}`).join(" "),
    durationBounds: generationDurationBoundsForModel(mode, option),
    aspectOptions: aspectOptions.join(" "),
    resolutionOptions: resolutionOptions.map((resolution) => resolutionRow(mode, resolution)),
    qualityOptions: qualityOptions.map(
      (quality) => `${quality}=${generationQualityLabel(quality)}`,
    ),
    voiceOptions: voiceOptions.join(" "),
    selectedVoice: selectedGenerationVoice(mode, option, ""),
    maxImages: generationModelMaxImages(mode, option),
    settingsWithAudio: settings(true),
    settingsWithoutAudio: settings(false),
  };
}

function matrix(
  mode: MediaGenerationMode,
  options: readonly GenerationModelOption[],
  providers?: readonly string[],
  excludeProviders?: readonly string[],
) {
  return options
    .filter((option) => !providers || providers.includes(option.provider))
    .filter((option) => !excludeProviders || !excludeProviders.includes(option.provider))
    .map((option) => settingsRow(mode, option));
}

const catalogVideoOption: GenerationModelOption = {
  provider: "catalog",
  id: "catalog-video",
  durations: [3, 6],
  aspectRatios: ["21:9", "1:1"],
  resolutions: ["480p", "580p", "720p", "1080p", "4k", "4K", "1K", "2K", "640x360", "weird"],
};

const catalogImageOption: GenerationModelOption = {
  provider: "catalog",
  id: "catalog-image",
  aspectRatios: ["4:5"],
  resolutions: ["1K", "2K", "4K", "2048x1152"],
  qualities: ["low", "high_detail"],
  maxImages: 3.7,
};

const catalogAudioOption: GenerationModelOption = {
  provider: "catalog",
  id: "catalog-audio",
  category: " music ",
  voices: ["deep", "bright"],
  defaultVoice: " bright ",
  supportsLyrics: true,
  supportsInstrumental: true,
  supportsStyleInstructions: true,
  minSeconds: 10,
  maxSeconds: 60,
};

const catalogVoiceSampleOption: GenerationModelOption = {
  provider: "catalog",
  id: "catalog-tts",
  category: "tts",
  voicesSample: ["sample-a"],
  minSeconds: 120,
  maxSeconds: 600,
};

describe("generation settings option matrix", () => {
  it("records image fal.ai options", () => {
    expect(matrix("image", generationModelOptions.image, ["fal.ai"])).toMatchInlineSnapshot(`
      [
        {
          "aspectOptions": "auto 21:9 16:9 3:2 4:3 5:4 1:1 4:5 3:4 2:3 9:16",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 1,
          "model": "fal.ai:fal-ai/nano-banana-pro/edit",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=Landscape 1280p",
            "1536x864 1536x864 provider=1080p label=- display=Landscape",
            "1080x1920 1080x1920 provider=1080p label=- display=Portrait 1080p",
            "1024x1024 1024x1024 provider=720p label=- display=Square",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "auto",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "2K",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "auto",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "2K",
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 4,
          "model": "fal.ai:fal-ai/flux/schnell",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=Landscape 1280p",
            "1536x864 1536x864 provider=1080p label=- display=Landscape",
            "1080x1920 1080x1920 provider=1080p label=- display=Portrait 1080p",
            "1024x1024 1024x1024 provider=720p label=- display=Square",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "1:1 16:9 9:16 4:3 3:4",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 1,
          "model": "fal.ai:fal-ai/krea-2/turbo",
          "qualityOptions": [],
          "resolutionOptions": [
            "1024x1024 1024x1024 provider=1024x1024 label=- display=Square",
            "1024x576 1024x576 provider=1024x576 label=- display=Landscape",
            "576x1024 576x1024 provider=576x1024 label=- display=Portrait",
            "1024x768 1024x768 provider=1024x768 label=- display=Landscape",
            "768x1024 768x1024 provider=768x1024 label=- display=Portrait",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "1:1",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 1024,
            "numImages": 1,
            "resolution": "1024x1024",
            "width": 1024,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "1:1",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 1024,
            "numImages": 1,
            "resolution": "1024x1024",
            "width": 1024,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "1:1 16:9 9:16 4:3 3:4",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 1,
          "model": "fal.ai:fal-ai/recraft/v3/text-to-image",
          "qualityOptions": [
            "realistic_image=Realistic Image",
            "digital_illustration=Digital Illustration",
            "vector_illustration=Vector Illustration",
          ],
          "resolutionOptions": [
            "1024x1024 1024x1024 provider=1024x1024 label=- display=Square",
            "1280x720 1280x720 provider=1280x720 label=- display=Landscape 1280p",
            "720x1280 720x1280 provider=720x1280 label=- display=Portrait 1280p",
            "1280x960 1280x960 provider=1280x960 label=- display=Landscape 1280p",
            "960x1280 960x1280 provider=960x1280 label=- display=Portrait 1280p",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "1:1",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 1024,
            "numImages": 1,
            "quality": "realistic_image",
            "resolution": "1024x1024",
            "width": 1024,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "1:1",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 1024,
            "numImages": 1,
            "quality": "realistic_image",
            "resolution": "1024x1024",
            "width": 1024,
          },
          "voiceOptions": "",
        },
      ]
    `);
  });

  it("records non-fal image options", () => {
    expect(
      matrix("image", generationModelOptions.image, undefined, ["fal.ai"]),
    ).toMatchInlineSnapshot(`
      [
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 4,
          "model": "openai:gpt-image-2",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=Landscape 1280p",
            "1536x864 1536x864 provider=1080p label=- display=Landscape",
            "1080x1920 1080x1920 provider=1080p label=- display=Portrait 1080p",
            "1024x1024 1024x1024 provider=720p label=- display=Square",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "1280x720",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "1280x720",
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 4,
          "model": "replicate:black-forest-labs/flux-schnell",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=Landscape 1280p",
            "1536x864 1536x864 provider=1080p label=- display=Landscape",
            "1080x1920 1080x1920 provider=1080p label=- display=Portrait 1080p",
            "1024x1024 1024x1024 provider=720p label=- display=Square",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 1,
          "model": "replicate:black-forest-labs/flux-dev",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=Landscape 1280p",
            "1536x864 1536x864 provider=1080p label=- display=Landscape",
            "1080x1920 1080x1920 provider=1080p label=- display=Portrait 1080p",
            "1024x1024 1024x1024 provider=720p label=- display=Square",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 1,
          "model": "replicate:black-forest-labs/flux-1.1-pro",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=Landscape 1280p",
            "1536x864 1536x864 provider=1080p label=- display=Landscape",
            "1080x1920 1080x1920 provider=1080p label=- display=Portrait 1080p",
            "1024x1024 1024x1024 provider=720p label=- display=Square",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 1,
          "model": "replicate:black-forest-labs/flux-1.1-pro-ultra",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=Landscape 1280p",
            "1536x864 1536x864 provider=1080p label=- display=Landscape",
            "1080x1920 1080x1920 provider=1080p label=- display=Portrait 1080p",
            "1024x1024 1024x1024 provider=720p label=- display=Square",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 1,
          "model": "openai:gpt-image-1.5",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=Landscape 1280p",
            "1536x864 1536x864 provider=1080p label=- display=Landscape",
            "1080x1920 1080x1920 provider=1080p label=- display=Portrait 1080p",
            "1024x1024 1024x1024 provider=720p label=- display=Square",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "auto",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "auto",
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 1,
          "model": "xai:grok-imagine-image-quality",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=Landscape 1280p",
            "1536x864 1536x864 provider=1080p label=- display=Landscape",
            "1080x1920 1080x1920 provider=1080p label=- display=Portrait 1080p",
            "1024x1024 1024x1024 provider=720p label=- display=Square",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 720,
            "numImages": 1,
            "resolution": "720p",
            "width": 1280,
          },
          "voiceOptions": "",
        },
      ]
    `);
  });

  it("records fal.ai video options", () => {
    expect(matrix("video", generationModelOptions.video, ["fal.ai"])).toMatchInlineSnapshot(`
      [
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "5s=5 10s=10",
          "maxImages": 1,
          "model": "fal.ai:fal-ai/wan-25-preview/text-to-video",
          "qualityOptions": [],
          "resolutionOptions": [
            "480p 854x480 provider=480p label=- display=480p",
            "720p 1280x720 provider=720p label=- display=720p",
            "1080p 1920x1080 provider=1080p label=- display=1080p",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": true,
            "height": 480,
            "resolution": "480p",
            "width": 854,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": false,
            "height": 480,
            "resolution": "480p",
            "width": 854,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "5s=5 10s=10",
          "maxImages": 1,
          "model": "fal.ai:fal-ai/wan/v2.7/image-to-video",
          "qualityOptions": [],
          "resolutionOptions": [
            "480p 854x480 provider=480p label=- display=480p",
            "720p 1280x720 provider=720p label=- display=720p",
            "1080p 1920x1080 provider=1080p label=- display=1080p",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": true,
            "height": 480,
            "resolution": "480p",
            "width": 854,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": false,
            "height": 480,
            "resolution": "480p",
            "width": 854,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1 4:3 3:4",
          "durationBounds": null,
          "durationOptions": "2s=2 3s=3 4s=4 5s=5 6s=6 7s=7 8s=8 9s=9 10s=10",
          "maxImages": 1,
          "model": "fal.ai:fal-ai/wan/v2.7/reference-to-video",
          "qualityOptions": [],
          "resolutionOptions": [
            "720p 1280x720 provider=720p label=- display=720p",
            "1080p 1920x1080 provider=1080p label=- display=1080p",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 2,
            "fps": 24,
            "generateAudio": true,
            "height": 720,
            "resolution": "720p",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 2,
            "fps": 24,
            "generateAudio": false,
            "height": 720,
            "resolution": "720p",
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "auto 16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "5s=5 10s=10",
          "maxImages": 1,
          "model": "fal.ai:fal-ai/wan/v2.2-a14b/video-to-video",
          "qualityOptions": [],
          "resolutionOptions": [
            "480p 854x480 provider=480p label=- display=480p",
            "580p 1032x580 provider=580p label=- display=580p",
            "720p 1280x720 provider=720p label=- display=720p",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "auto",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": true,
            "height": 480,
            "resolution": "480p",
            "width": 854,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "auto",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": true,
            "height": 480,
            "resolution": "480p",
            "width": 854,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "5s=5 10s=10",
          "maxImages": 1,
          "model": "fal.ai:fal-ai/kling-video/v3/standard/text-to-video",
          "qualityOptions": [],
          "resolutionOptions": [],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": true,
            "height": 720,
            "resolution": null,
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": false,
            "height": 720,
            "resolution": null,
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "5s=5 10s=10",
          "maxImages": 1,
          "model": "fal.ai:fal-ai/kling-video/v3/pro/image-to-video",
          "qualityOptions": [],
          "resolutionOptions": [],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": true,
            "height": 720,
            "resolution": null,
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": false,
            "height": 720,
            "resolution": null,
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "5s=5 10s=10",
          "maxImages": 1,
          "model": "fal.ai:fal-ai/kling-video/v3/pro/motion-control",
          "qualityOptions": [],
          "resolutionOptions": [],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": true,
            "height": 720,
            "resolution": null,
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": false,
            "height": 720,
            "resolution": null,
            "width": 1280,
          },
          "voiceOptions": "",
        },
      ]
    `);
  });

  it("records non-fal video options", () => {
    expect(
      matrix("video", generationModelOptions.video, undefined, ["fal.ai"]),
    ).toMatchInlineSnapshot(`
      [
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "5s=5 10s=10",
          "maxImages": 1,
          "model": "replicate:bytedance/seedance-2.0-fast",
          "qualityOptions": [],
          "resolutionOptions": [
            "720p 1280x720 provider=720p label=- display=720p",
            "1080p 1920x1080 provider=1080p label=- display=1080p",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": true,
            "height": 720,
            "resolution": "720p",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": false,
            "height": 720,
            "resolution": "720p",
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1",
          "durationBounds": null,
          "durationOptions": "5s=5 10s=10",
          "maxImages": 1,
          "model": "replicate:bytedance/seedance-2.0",
          "qualityOptions": [],
          "resolutionOptions": [
            "720p 1280x720 provider=720p label=- display=720p",
            "1080p 1920x1080 provider=1080p label=- display=1080p",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": true,
            "height": 720,
            "resolution": "720p",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 5,
            "fps": 24,
            "generateAudio": false,
            "height": 720,
            "resolution": "720p",
            "width": 1280,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16 1:1 4:3 3:4 3:2 2:3",
          "durationBounds": null,
          "durationOptions": "1s=1 2s=2 3s=3 4s=4 5s=5 6s=6 7s=7 8s=8 9s=9 10s=10 11s=11 12s=12 13s=13 14s=14 15s=15",
          "maxImages": 1,
          "model": "xai:grok-imagine-video",
          "qualityOptions": [],
          "resolutionOptions": [
            "480p 854x480 provider=480p label=- display=480p",
            "720p 1280x720 provider=720p label=- display=720p",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 1,
            "fps": 24,
            "generateAudio": true,
            "height": 480,
            "resolution": "480p",
            "width": 854,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 1,
            "fps": 24,
            "generateAudio": true,
            "height": 480,
            "resolution": "480p",
            "width": 854,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "16:9 9:16",
          "durationBounds": null,
          "durationOptions": "8s=8",
          "maxImages": 1,
          "model": "google:veo3.1-fast",
          "qualityOptions": [],
          "resolutionOptions": [
            "720p 1280x720 provider=720p label=- display=720p",
            "1080p 1920x1080 provider=1080p label=- display=1080p",
            "4k 3840x2160 provider=4k label=4K display=4K",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 8,
            "fps": 24,
            "generateAudio": true,
            "height": 720,
            "resolution": "720p",
            "width": 1280,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "16:9",
            "durationSeconds": 8,
            "fps": 24,
            "generateAudio": false,
            "height": 720,
            "resolution": "720p",
            "width": 1280,
          },
          "voiceOptions": "",
        },
      ]
    `);
  });

  it("records audio options", () => {
    expect(matrix("audio", generationModelOptions.audio)).toMatchInlineSnapshot(`
      [
        {
          "aspectOptions": "",
          "durationBounds": null,
          "durationOptions": "",
          "maxImages": 1,
          "model": "fal.ai:bytedance/seed-audio-1.0",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": null,
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "width": null,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "",
          "durationBounds": {
            "defaultSeconds": 90,
            "maxSeconds": 600,
            "minSeconds": 1,
          },
          "durationOptions": "",
          "maxImages": 1,
          "model": "fal.ai:sonilo/v1.1/text-to-music",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": null,
            "category": "music",
            "durationSeconds": 90,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "instrumental": false,
            "resolution": null,
            "styleInstructions": "warm",
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "category": "music",
            "durationSeconds": 90,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "instrumental": false,
            "resolution": null,
            "styleInstructions": "warm",
            "width": null,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "",
          "durationBounds": null,
          "durationOptions": "",
          "maxImages": 1,
          "model": "fal.ai:sonilo/v1.1/video-to-music",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": null,
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "width": null,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "",
          "durationBounds": null,
          "durationOptions": "",
          "maxImages": 1,
          "model": "fal.ai:mirelo-ai/sfx-v1.5/video-to-audio",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": null,
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "width": null,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "",
          "durationBounds": null,
          "durationOptions": "",
          "maxImages": 1,
          "model": "openai:gpt-4o-mini-tts",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "alloy",
          "settingsWithAudio": {
            "aspectRatio": null,
            "category": "tts",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "styleInstructions": "warm",
            "voice": "",
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "category": "tts",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "styleInstructions": "warm",
            "voice": "",
            "width": null,
          },
          "voiceOptions": "alloy ash ballad cedar coral echo fable marin nova onyx sage shimmer verse",
        },
        {
          "aspectOptions": "",
          "durationBounds": null,
          "durationOptions": "",
          "maxImages": 1,
          "model": "elevenlabs:elevenlabs-tts-v3",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "rachel",
          "settingsWithAudio": {
            "aspectRatio": null,
            "category": "tts",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "styleInstructions": "warm",
            "voice": "",
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "category": "tts",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "styleInstructions": "warm",
            "voice": "",
            "width": null,
          },
          "voiceOptions": "rachel",
        },
        {
          "aspectOptions": "",
          "durationBounds": {
            "defaultSeconds": 90,
            "maxSeconds": 600,
            "minSeconds": 3,
          },
          "durationOptions": "",
          "maxImages": 1,
          "model": "elevenlabs:elevenlabs-music",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": null,
            "category": "music",
            "durationSeconds": 90,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "instrumental": false,
            "lyrics": "la la",
            "resolution": null,
            "styleInstructions": "warm",
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "category": "music",
            "durationSeconds": 90,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "instrumental": false,
            "lyrics": "la la",
            "resolution": null,
            "styleInstructions": "warm",
            "width": null,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "",
          "durationBounds": null,
          "durationOptions": "",
          "maxImages": 1,
          "model": "minimax:minimax-music-v2.6",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": null,
            "category": "music",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "instrumental": false,
            "lyrics": "la la",
            "resolution": null,
            "styleInstructions": "warm",
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "category": "music",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "instrumental": false,
            "lyrics": "la la",
            "resolution": null,
            "styleInstructions": "warm",
            "width": null,
          },
          "voiceOptions": "",
        },
        {
          "aspectOptions": "",
          "durationBounds": null,
          "durationOptions": "",
          "maxImages": 1,
          "model": "google:gemini-3.1-flash-tts-preview",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "Kore",
          "settingsWithAudio": {
            "aspectRatio": null,
            "category": "tts",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "styleInstructions": "warm",
            "voice": "",
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "category": "tts",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "styleInstructions": "warm",
            "voice": "",
            "width": null,
          },
          "voiceOptions": "Zephyr Puck Charon Kore Fenrir Leda Orus Aoede Callirrhoe Autonoe Enceladus Iapetus Umbriel Algieba Despina Erinome Algenib Rasalgethi Laomedeia Achernar Alnilam Schedar Gacrux Pulcherrima Achird Zubenelgenubi Vindemiatrix Sadachbia Sadaltager Sulafat",
        },
        {
          "aspectOptions": "",
          "durationBounds": null,
          "durationOptions": "",
          "maxImages": 1,
          "model": "google:lyria3-pro",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": null,
            "category": "music",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "instrumental": false,
            "lyrics": "la la",
            "resolution": null,
            "styleInstructions": "warm",
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "category": "music",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "instrumental": false,
            "lyrics": "la la",
            "resolution": null,
            "styleInstructions": "warm",
            "width": null,
          },
          "voiceOptions": "",
        },
      ]
    `);
  });

  it("records catalog-driven options", () => {
    expect({
      video: settingsRow("video", catalogVideoOption),
      image: settingsRow("image", catalogImageOption),
      audio: settingsRow("audio", catalogAudioOption),
      voiceSample: settingsRow("audio", catalogVoiceSampleOption),
    }).toMatchInlineSnapshot(`
      {
        "audio": {
          "aspectOptions": "",
          "durationBounds": {
            "defaultSeconds": 60,
            "maxSeconds": 60,
            "minSeconds": 10,
          },
          "durationOptions": "",
          "maxImages": 1,
          "model": "catalog:catalog-audio",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "bright",
          "settingsWithAudio": {
            "aspectRatio": null,
            "category": "music",
            "durationSeconds": 60,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "instrumental": false,
            "lyrics": "la la",
            "resolution": null,
            "styleInstructions": "warm",
            "voice": "",
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "category": "music",
            "durationSeconds": 60,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "instrumental": false,
            "lyrics": "la la",
            "resolution": null,
            "styleInstructions": "warm",
            "voice": "",
            "width": null,
          },
          "voiceOptions": "deep bright",
        },
        "image": {
          "aspectOptions": "4:5",
          "durationBounds": null,
          "durationOptions": "4s=4 8s=8 12s=12",
          "maxImages": 3,
          "model": "catalog:catalog-image",
          "qualityOptions": [
            "low=Low",
            "high_detail=High Detail",
          ],
          "resolutionOptions": [
            "1K 1024x1024 provider=1K label=- display=Square",
            "2K 2048x2048 provider=2K label=- display=Square",
            "4K 3840x2160 provider=4K label=4K display=4K",
            "2048x1152 2048x1152 provider=2048x1152 label=- display=Landscape 2048p",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "4:5",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 1024,
            "numImages": 1,
            "quality": "low",
            "resolution": "1K",
            "width": 1024,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "4:5",
            "durationSeconds": null,
            "fps": null,
            "generateAudio": null,
            "height": 1024,
            "numImages": 1,
            "quality": "low",
            "resolution": "1K",
            "width": 1024,
          },
          "voiceOptions": "",
        },
        "video": {
          "aspectOptions": "21:9 1:1",
          "durationBounds": null,
          "durationOptions": "3s=3 6s=6",
          "maxImages": 1,
          "model": "catalog:catalog-video",
          "qualityOptions": [],
          "resolutionOptions": [
            "480p 854x480 provider=480p label=- display=480p",
            "580p 1032x580 provider=580p label=- display=580p",
            "720p 1280x720 provider=720p label=- display=720p",
            "1080p 1920x1080 provider=1080p label=- display=1080p",
            "4k 3840x2160 provider=4k label=4K display=4K",
            "4K 3840x2160 provider=4K label=4K display=4K",
            "1K 1024x1024 provider=1K label=- display=1K",
            "2K 2048x2048 provider=2K label=- display=2K",
            "640x360 640x360 provider=640x360 label=- display=640x360",
            "weird 1280x720 provider=weird label=- display=weird",
          ],
          "selectedVoice": "",
          "settingsWithAudio": {
            "aspectRatio": "21:9",
            "durationSeconds": 3,
            "fps": 24,
            "generateAudio": true,
            "height": 480,
            "resolution": "480p",
            "width": 1120,
          },
          "settingsWithoutAudio": {
            "aspectRatio": "21:9",
            "durationSeconds": 3,
            "fps": 24,
            "generateAudio": true,
            "height": 480,
            "resolution": "480p",
            "width": 1120,
          },
          "voiceOptions": "",
        },
        "voiceSample": {
          "aspectOptions": "",
          "durationBounds": {
            "defaultSeconds": 120,
            "maxSeconds": 600,
            "minSeconds": 120,
          },
          "durationOptions": "",
          "maxImages": 1,
          "model": "catalog:catalog-tts",
          "qualityOptions": [],
          "resolutionOptions": [
            "1280x720 1280x720 provider=720p label=- display=1280x720",
            "1536x864 1536x864 provider=1080p label=- display=1536x864",
            "1080x1920 1080x1920 provider=1080p label=- display=1080x1920",
            "1024x1024 1024x1024 provider=720p label=- display=1024x1024",
          ],
          "selectedVoice": "sample-a",
          "settingsWithAudio": {
            "aspectRatio": null,
            "category": "tts",
            "durationSeconds": 120,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "voice": "",
            "width": null,
          },
          "settingsWithoutAudio": {
            "aspectRatio": null,
            "category": "tts",
            "durationSeconds": 120,
            "fps": null,
            "generateAudio": null,
            "height": null,
            "resolution": null,
            "voice": "",
            "width": null,
          },
          "voiceOptions": "sample-a",
        },
      }
    `);
  });
});

describe("generation settings value helpers", () => {
  it("records duration values and bounds", () => {
    const bounds = { minSeconds: 3, maxSeconds: 600, defaultSeconds: 90 };
    expect({
      durationValue: [4, 8, 5, null].map((seconds) => generationDurationValue(seconds)),
      durationValueCustomOptions: generationDurationValue(10, [{ value: "10s", seconds: 10 }]),
      boundedValue: [null, 0, -2, Number.NaN, 12.4, 12.5].map((seconds) =>
        boundedGenerationDurationValue(seconds),
      ),
      boundedSeconds: ["", "  45 ", "8s", "1", "1000", "abc", "12.6"].map((value) =>
        selectedBoundedGenerationDurationSeconds(value, bounds),
      ),
      boundedSecondsWithoutBounds: selectedBoundedGenerationDurationSeconds("12", null),
      boundedValueStrings: ["", "30", "9000"].map((value) =>
        selectedBoundedGenerationDurationValue(value, bounds),
      ),
      boundedValueWithoutBounds: selectedBoundedGenerationDurationValue("30", null),
    }).toMatchInlineSnapshot(`
      {
        "boundedSeconds": [
          90,
          45,
          90,
          3,
          600,
          90,
          13,
        ],
        "boundedSecondsWithoutBounds": null,
        "boundedValue": [
          null,
          null,
          null,
          null,
          "12",
          "13",
        ],
        "boundedValueStrings": [
          "90",
          "30",
          "600",
        ],
        "boundedValueWithoutBounds": "",
        "durationValue": [
          "4s",
          "8s",
          null,
          null,
        ],
        "durationValueCustomOptions": "10s",
      }
    `);
  });

  it("records resolution, aspect and quality values", () => {
    const videoOptions = generationResolutionOptionsForModel("video", {
      provider: "google",
      id: googleVeo31FastModelId,
    });
    const wanVideoToVideoOptions = generationResolutionOptionsForModel("video", {
      provider: "fal.ai",
      id: falWanVideoToVideoModelId,
    });
    expect({
      fallbackVideoResolutionOption,
      resolutionValue: [
        [1280, 720],
        [1536, 864],
        [3840, 2160],
        [2000, 1000],
        [640, 360],
        [null, 720],
      ].map(([width, height]) => generationResolutionValue(width ?? null, height ?? null)),
      resolutionValueVideoOptions: [
        [3840, 2160],
        [1920, 1080],
        [1000, 500],
        [640, 360],
      ].map(([width, height]) =>
        generationResolutionValue(width ?? null, height ?? null, videoOptions),
      ),
      resolutionValueWanVideoToVideo: [
        [640, 360],
        [1200, 700],
        [2000, 1000],
      ].map(([width, height]) =>
        generationResolutionValue(width ?? null, height ?? null, wanVideoToVideoOptions),
      ),
      selectedResolution: ["720p", "1536x864", "1280x720", "1024x1024", "missing", ""].map(
        (value) => selectedGenerationResolutionValue(value, videoOptions),
      ),
      selectedResolutionEmptyOptions: selectedGenerationResolutionValue("720p", []),
      aspectRatios: ["16:9", "auto", "21:9", "2:3", "5:1", null].map((value) =>
        isGenerationAspectRatio(value),
      ),
      qualityValue: [
        selectedGenerationQualityValue("digital_illustration", ["realistic_image", "digital_illustration"]),
        selectedGenerationQualityValue("missing", ["realistic_image", "digital_illustration"]),
        selectedGenerationQualityValue("anything", []),
      ],
      qualityLabels: ["vector_illustration", "high", "", "a__b"].map((value) =>
        generationQualityLabel(value),
      ),
      resolutionLabels: [
        { value: "1024x1024", width: 1024, height: 1024, providerResolution: "1024x1024" },
        { value: "3840x2160", width: 3840, height: 2160, providerResolution: "4K" },
        { value: "1440x2560", width: 1440, height: 2560, providerResolution: "2K" },
        { value: "1080x1920", width: 1080, height: 1920, providerResolution: "1080p" },
        { value: "1536x864", width: 1536, height: 864, providerResolution: "1080p" },
        { value: "960x1280", width: 960, height: 1280, providerResolution: "960x1280" },
        { value: "4k", label: "4K", width: 3840, height: 2160, providerResolution: "4k" },
      ].map((option) => ({
        image: generationResolutionLabel("image", option),
        video: generationResolutionLabel("video", option),
      })),
    }).toMatchInlineSnapshot(`
      {
        "aspectRatios": [
          true,
          true,
          true,
          true,
          false,
          false,
        ],
        "fallbackVideoResolutionOption": {
          "height": 720,
          "providerResolution": "720p",
          "value": "720p",
          "width": 1280,
        },
        "qualityLabels": [
          "Vector Illustration",
          "High",
          "",
          "A  B",
        ],
        "qualityValue": [
          "digital_illustration",
          "digital_illustration",
          null,
        ],
        "resolutionLabels": [
          {
            "image": "Square",
            "video": "1024x1024",
          },
          {
            "image": "Landscape 4K",
            "video": "3840x2160",
          },
          {
            "image": "Portrait 2K",
            "video": "1440x2560",
          },
          {
            "image": "Portrait 1080p",
            "video": "1080x1920",
          },
          {
            "image": "Landscape",
            "video": "1536x864",
          },
          {
            "image": "Portrait 1280p",
            "video": "960x1280",
          },
          {
            "image": "4K",
            "video": "4K",
          },
        ],
        "resolutionValue": [
          "1280x720",
          "1536x864",
          null,
          null,
          null,
          null,
        ],
        "resolutionValueVideoOptions": [
          "4k",
          "1080p",
          "720p",
          "720p",
        ],
        "resolutionValueWanVideoToVideo": [
          "480p",
          "720p",
          "720p",
        ],
        "selectedResolution": [
          "720p",
          "1080p",
          "720p",
          "720p",
          "720p",
          "720p",
        ],
        "selectedResolutionEmptyOptions": "",
      }
    `);
  });

  it("records image counts, provider resolutions and voices", () => {
    const resolutions: GenerationResolutionOption[] = [
      { value: "1024x1024", width: 1024, height: 1024, providerResolution: "720p" },
      { value: "1536x1024", width: 1536, height: 1024, providerResolution: "1080p" },
      { value: "2048x2048", width: 2048, height: 2048, providerResolution: "2K" },
      { value: "3840x2160", width: 3840, height: 2160, providerResolution: "4K" },
    ];
    const imageModels = [
      { provider: "fal.ai", id: falNanoBananaProEditModelId },
      { provider: "openai", id: openAiGptImage2ModelId },
      { provider: "openai", id: openAiGptImageEditModelId },
      { provider: "fal.ai", id: falFluxSchnellModelId },
    ];
    expect({
      imageCounts: ["", "0", "2", "3", "9", "abc", "2.9"].map((value) => ({
        value,
        schnell: selectedImageCount("image", { provider: "fal.ai", id: falFluxSchnellModelId }, value),
        videoMode: selectedImageCount("video", { provider: "fal.ai", id: falFluxSchnellModelId }, value),
        single: selectedImageCount("image", { provider: "xai", id: xAiGrokImageQualityModelId }, value),
      })),
      maxImages: [
        generationModelMaxImages("image", { provider: "x", id: "y", maxImages: 0 }),
        generationModelMaxImages("image", { provider: "x", id: "y", maxImages: Number.NaN }),
        generationModelMaxImages("image", { provider: "x", id: "y", maxImages: 2.2 }),
        generationModelMaxImages("audio", { provider: "x", id: "y", maxImages: 8 }),
      ],
      providerResolutions: imageModels.map((model) => ({
        model: `${model.provider}:${model.id}`,
        values: resolutions.map((resolution) => imageGenerationProviderResolution(model, resolution)),
      })),
      voices: [
        selectedGenerationVoice("audio", { provider: "openai", id: openAiTtsModelId }, "nova"),
        selectedGenerationVoice("audio", { provider: "openai", id: openAiTtsModelId }, "missing"),
        selectedGenerationVoice("audio", { provider: "google", id: googleGeminiTtsModelId }, ""),
        selectedGenerationVoice("audio", { provider: "elevenlabs", id: elevenLabsTtsModelId }, ""),
        selectedGenerationVoice("audio", catalogAudioOption, "deep"),
        selectedGenerationVoice("audio", catalogAudioOption, "missing"),
        selectedGenerationVoice("video", { provider: "openai", id: openAiTtsModelId }, "nova"),
        selectedGenerationVoice("video", catalogAudioOption, "deep"),
        selectedGenerationVoice("audio", { provider: "none", id: "none" }, "anything"),
      ],
    }).toMatchInlineSnapshot(`
      {
        "imageCounts": [
          {
            "schnell": 1,
            "single": 1,
            "value": "",
            "videoMode": 1,
          },
          {
            "schnell": 1,
            "single": 1,
            "value": "0",
            "videoMode": 1,
          },
          {
            "schnell": 2,
            "single": 1,
            "value": "2",
            "videoMode": 1,
          },
          {
            "schnell": 3,
            "single": 1,
            "value": "3",
            "videoMode": 1,
          },
          {
            "schnell": 4,
            "single": 1,
            "value": "9",
            "videoMode": 1,
          },
          {
            "schnell": 1,
            "single": 1,
            "value": "abc",
            "videoMode": 1,
          },
          {
            "schnell": 2,
            "single": 1,
            "value": "2.9",
            "videoMode": 1,
          },
        ],
        "maxImages": [
          1,
          1,
          2,
          1,
        ],
        "providerResolutions": [
          {
            "model": "fal.ai:fal-ai/nano-banana-pro/edit",
            "values": [
              "1K",
              "2K",
              "2K",
              "4K",
            ],
          },
          {
            "model": "openai:gpt-image-2",
            "values": [
              "1024x1024",
              "1536x1024",
              "2048x2048",
              "3840x2160",
            ],
          },
          {
            "model": "openai:gpt-image-1.5",
            "values": [
              "1024x1024",
              "1536x1024",
              "auto",
              "auto",
            ],
          },
          {
            "model": "fal.ai:fal-ai/flux/schnell",
            "values": [
              "720p",
              "1080p",
              "2K",
              "4K",
            ],
          },
        ],
        "voices": [
          "nova",
          "alloy",
          "Kore",
          "rachel",
          "deep",
          "bright",
          "alloy",
          "",
          "",
        ],
      }
    `);
  });
});
